### ISSUE TITLE
Unideal Gentoo Download instructions

### ISSUE THREAD

**Issue by samuel-garmany** [polychromatic/docs#1]
I tried to fork it but I don't know how to use github very well so I'll leave the issue here, the use of layman in this page (https://polychromatic.app/download/gentoo/) is no longer the recommended format to add repositories, the command should be `eselect repository enable vifino-overlay` followed by `emaint sync -r vifino-overlay` and then the final emerge command

**Comment by lah7** [comment]
Thanks for the info. I've updated the website as well as OpenRazer's (as I maintain both).

For future editing - the file is over on the website repository at [pages/download/gentoo.md](https://github.com/polychromatic/website/blob/master/pages/download/gentoo.md), it's then possible to click the ✏️ pencil to edit the file and have GitHub fork/commit/propose changes for you. :+1:
